default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "db" } %>
  username: <%= ENV.fetch("DATABASE_USER") { "postgres" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "password" } %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { "smart_shift_planner_development" } %>

test:
  <<: *default
  database: smart_shift_planner_test

production:
  url: <%= ENV["DATABASE_URL"] %>
